server.port=8082
spring.application.name=tournament-service

spring.datasource.url=jdbc:postgresql://localhost:5432/tournament_db
spring.datasource.username=Davel45
spring.datasource.password=123321

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

resilience4j.retry.instances.externalService.max-attempts=3
resilience4j.retry.instances.externalService.wait-duration=1s

resilience4j.circuitbreaker.instances.externalService.sliding-window-size=5
resilience4j.circuitbreaker.instances.externalService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.externalService.wait-duration-in-open-state=10s

management.tracing.sampling.probability=1.0

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user
spring.rabbitmq.password=password